version: '3.8'

services:
  wisereminder.webapi:
    image: wisereminder.webapi
    container_name: webapi
    build:
      context: .
      dockerfile: src/WiseReminder.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__RedisConnection=redis:6379
      - ConnectionStrings__DbConnection=Host=postgres;Port=5432;Database=wisereminder;Username=postgres;Password=123456
      - ConnectionStrings__SeqConnection=http://seq:5341/
      - JWTPassword=ThisIsSpecialSecurityKeyThisIsSpecialSecurityKeyThisIsSpecialSecurityKeyThisIsSpecialSecurityKey
      - AllowMigrations=true
      - AllowSeeding=true
      - AllowScalar=true
    env_file:
      - secrets.env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      seq:
        condition: service_started
  
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wisereminder
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:5341"
    restart: always