version: '3.8'

services:
  wisereminder.webapi:
    image: wisereminder.webapi
    container_name: webapi
    build:
      context: .
      dockerfile: src/WiseReminder.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__RedisConnection=redis:6379
      - ConnectionStrings__DbConnection=Host=postgres;Port=5432;Database=wisereminder;Username=postgres;Password=123456
      - ConnectionStrings__SeqConnection=http://seq:5341/
      - JWTPassword=ThisIsSpecialSecurityKeyThisIsSpecialSecurityKeyThisIsSpecialSecurityKeyThisIsSpecialSecurityKey
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
      - seq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wise_reminder
    ports:
      - "5432:5432"

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:5341"