namespace WiseReminder.ArchitectureTests;

public sealed class SealedModificatorTests(ITestOutputHelper testOutputHelper)
{
    [Fact]
    public void PresentationLayerClasses_ShouldBeSealedOrAbstract()
    {
        ValidateClasses(typeof(PresentationExtensions));
    }

    [Fact]
    public void ApplicationLayerClasses_ShouldBeSealedOrAbstract()
    {
        ValidateClasses(typeof(ApplicationExtensions));
    }

    [Fact]
    public void DomainLayerClasses_ShouldBeSealedOrAbstract()
    {
        ValidateClasses(typeof(Entity<>));
    }

    [Fact]
    public void InfrastructureLayerClasses_ShouldBeSealedOrAbstract()
    {
        ValidateClasses(typeof(InfrastructureExtensions));
    }

    [Fact]
    public void ArchitectureTests_ShouldBeSealedOrAbstract()
    {
        ValidateClasses(typeof(SealedModificatorTests));
    }

    [Fact]
    public void DomainUnitTests_ShouldBeSealedOrAbstract()
    {
        ValidateClasses(typeof(CategoryData));
    }

    [Fact]
    public void IntegrationTests_ShouldBeSealedOrAbstract()
    {
        ValidateClasses(typeof(WebAppFactory));
    }

    private void ValidateClasses(Type referenceType)
    {
        var types = referenceType.Assembly
            .GetTypes()
            .Where(t => t.IsClass)
            .ToList();

        foreach (var type in types)
        {
            if (type.Name == "AutoGeneratedProgram")
            {
                continue;
            }

            var derivedTypes = types.Where(t => t.BaseType == type).ToList();
            var hasChildren = derivedTypes.Count != 0;

            if (type is { IsSealed: false, IsAbstract: false } && !hasChildren)
            {
                Assert.Fail($"Class {type.FullName} must be sealed, abstract, or have children");
            }

            if (type is { IsSealed: false, IsAbstract: false } && hasChildren)
            {
                testOutputHelper.WriteLine(
                    $"Class {type.FullName} is neither sealed nor abstract but has children");

                continue;
            }

            Assert.True(type.IsSealed || type.IsAbstract,
                $"Class {type.FullName} must be sealed or abstract");
        }
    }
}